### ISSUE TITLE
custom tag done via taskpaper-tag-faces not working

### ISSUE THREAD

**Issue by avelino** [saf-dmitry/taskpaper-mode#4]
```el
(setq taskpaper-tag-faces
      '(("done" . (:foreground "green" :weight bold)))
```

<img width="240" alt="screenshot 2018-03-08 22 02 59" src="https://user-images.githubusercontent.com/31996/37184910-80ca28d6-231c-11e8-9f8d-d62766592b85.png">

fix create new tag `@avelino` by example working:
<img width="265" alt="screenshot 2018-03-08 22 05 39" src="https://user-images.githubusercontent.com/31996/37184993-de482102-231c-11e8-8608-209c694d877f.png">

**Comment by saf-dmitry** [comment]
By design the formatting of done items (controlled by `taskpaper-item-marked-as-done-face`) takes precedence over the tag formatting i.e., _all_ tags in done items will loose their specific formatting. The intention is to visually "gray out" all the completed items incl. tags.

Now I have to think about this decision. Suggestions are welcome.

**Comment by saf-dmitry** [comment]
The fontification of done items is now configurable. The  `taskpaper-item-marked-as-done-face` face has been renamed to `taskpaper-done-item-face` and by default applies only strike-through formatting to completed items without overwriting other formatting like tags' colors etc.  If you customize the `taskpaper-done-item-face` by specifying any additional attribute like foreground, background, etc., it will take precedence over item's formatting, so it is still possible to visually "gray out" all the completed items incl. tags.

You also can disable the additional fontification of done items completely by setting the user option `taskpaper-fontify-done-items` to `nil`.
